apiVersion: v1
kind: Service
metadata:
  name: oliveyoung-api
  namespace: oliveyoung
  labels:
    app: oliveyoung-api
spec:
  type: ClusterIP
  selector:
    app: oliveyoung-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
